/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/academics` | `/academics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/fees` | `/fees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/classes` | `/classes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/discipline` | `/discipline`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(parent)'}/academics` | `/academics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(parent)'}/attendance` | `/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(parent)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(parent)'}/fees` | `/fees`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(parent)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/attendance` | `/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/classes` | `/classes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/discipline` | `/discipline`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(parent)'}/academics${`?${string}` | `#${string}` | ''}` | `/academics${`?${string}` | `#${string}` | ''}` | `${'/(parent)'}/attendance${`?${string}` | `#${string}` | ''}` | `/attendance${`?${string}` | `#${string}` | ''}` | `${'/(parent)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(parent)'}/fees${`?${string}` | `#${string}` | ''}` | `/fees${`?${string}` | `#${string}` | ''}` | `${'/(parent)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/attendance${`?${string}` | `#${string}` | ''}` | `/attendance${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/classes${`?${string}` | `#${string}` | ''}` | `/classes${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/discipline${`?${string}` | `#${string}` | ''}` | `/discipline${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/academics` | `/academics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/fees` | `/fees`; params?: Router.UnknownInputParams; } | { pathname: `${'/(parent)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/classes` | `/classes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/discipline` | `/discipline`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
