"use client";

import { useState } from "react";
import Link from "next/link";
import { Award } from "lucide-react";
import { FilterableDataTable } from "@/components/filterable-data-table";
import { EmptyState } from "@/components/empty-state";

interface StudentRow {
  id: string;
  name: string;
  admission: string;
  class_name: string;
  section: string;
}

interface HistoryRow {
  id: string;
  student_profile_id: string;
  student_name: string;
  class_name: string;
  academic_year: string;
  generated_by_name: string;
  generated_at: string;
}

interface Option { label: string; value: string }

export function CertificatesTable({
  students,
  history,
  classOptions,
  baseHref,
}: {
  students: StudentRow[];
  history: HistoryRow[];
  classOptions: Option[];
  baseHref: string;
}) {
  const [tab, setTab] = useState<"students" | "history">("students");

  return (
    <div className="space-y-4">
      <div className="flex gap-1 border-b border-border">
        {(["students", "history"] as const).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-4 py-2 text-sm font-medium capitalize transition-colors border-b-2 -mb-px ${
              tab === t ? "border-indigo-600 text-indigo-600" : "border-transparent text-muted-foreground hover:text-foreground"
            }`}
          >
            {t === "students" ? "Students" : "History"}
          </button>
        ))}
      </div>

      {tab === "students" ? (
        <FilterableDataTable
          data={students}
          columns={[
            { header: "Name", accessor: (row) => (
              <Link href={`/admin/students/${row.id}`} className="font-medium text-indigo-600 hover:underline">
                {row.name}
              </Link>
            ) },
            { header: "Admission No.", accessor: "admission" },
            { header: "Class", accessor: "class_name" },
            { header: "Section", accessor: "section" },
          ]}
          searchKeys={["name", "admission"]}
          searchPlaceholder="Search by name or admission number..."
          filter={
            classOptions.length > 0
              ? {
                  label: "All Classes",
                  options: classOptions,
                  filterFn: (row: StudentRow, value: string) => row.class_name === value,
                }
              : undefined
          }
          renderActions={(row) => (
            <Link
              href={`${baseHref}/${row.id}`}
              className="inline-flex items-center gap-1.5 rounded-md bg-indigo-50 px-2.5 py-1.5 text-xs font-medium text-indigo-700 hover:bg-indigo-100"
            >
              <Award className="h-3.5 w-3.5" />
              Generate
            </Link>
          )}
          emptyState={
            <EmptyState icon={Award} title="No students found" description="Add students to generate certificates." />
          }
        />
      ) : (
        <FilterableDataTable
          data={history}
          columns={[
            { header: "Student", accessor: (row) => (
              <Link href={`/admin/students/${row.student_profile_id}`} className="font-medium text-indigo-600 hover:underline">
                {row.student_name}
              </Link>
            ) },
            { header: "Class", accessor: "class_name" },
            { header: "Academic Year", accessor: "academic_year" },
            { header: "Generated By", accessor: "generated_by_name" },
            { header: "Date", accessor: "generated_at" },
          ]}
          searchKeys={["student_name"]}
          searchPlaceholder="Search by student name..."
          emptyState={
            <EmptyState icon={Award} title="No certificates issued yet" description="Generate a certificate to see history here." />
          }
        />
      )}
    </div>
  );
}
